name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: 3.11

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}

    steps:
      - uses: actions/checkout@v4
      - name: Installing poetry
        run: pip install poetry
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: poetry install
      - name: Caching dependencies
        id: cache-keys
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            /opt/pipx_bin/poetry
            /opt/pipx/venvs/poetry/bin/poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: poetry path
        run: |
          which poetry    

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache-dependency-path: '**/poetry.lock'
    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          /opt/pipx_bin/poetry
          /opt/pipx/venvs/poetry/bin/poetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
    - name: adding poetry to path
      run: |
        echo "/opt/pipx_bin" >> $GITHUB_PATH
    - name: test
      env:
        DJANGO_SETTINGS_MODULE: django_unchained.settings
      run: |
        poetry env list
