name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: 3.11

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Prepare dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    
    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true

    - name: Cache virtualenv and Poetry's cache
      uses: actions/cache@v3
      with:
        path: |
          ./.venv
          ~/.cache/pypoetry
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: |
        python -m poetry install

  test1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Restore Cache
      uses: actions/cache@v3
      with:
        path: |
          ./.venv
          ~/.cache/pypoetry
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: django_unchained.settings
      run: |
        python -m poetry run ./manage.py test

  test2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Restore Cache
      uses: actions/cache@v3
      with:
        path: |
          ./.venv
          ~/.cache/pypoetry
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-venv-${{ hashFiles('**/poetry.lock') }}
    - name: Run Tests 2
      env:
        DJANGO_SETTINGS_MODULE: django_unchained.settings
      run: |
        python -m poetry run ./manage.py test
