name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: 3.11
  
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.key }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Installing poetry
        run: pipx install poetry
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Determine cache key
        id: cache-keys
        run: echo "::set-output name=key::$(echo ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }})"
  