name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: 3.11

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install Poetry
      run: |
        pip install --upgrade pip
        pip install poetry

    - name: Cache Poetry
      uses: actions/cache@v3
      with:
        path: |
          ~/.poetry
        key: poetry
    
    - name: Add Poetry to $PATH
      run: |
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
    
    - name: Install dependencies
      run: poetry install

  test1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
          ~/.poetry
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
    # - name: Install Poetry
    #   run: pip install poetry
    - name: Check Poetry
      run: |
        ls -lah $HOME/
    # - name: Run Tests
    #   env:
    #     DJANGO_SETTINGS_MODULE: django_unchained.settings
    #   run: python -m poetry run ./manage.py test
        
  test2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pypoetry
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-poetry-${{ hashFiles('**/poetry.lock') }}
    - name: Check Poetry
      run: |
        ls -lah $HOME/
        echo "------------------"
        ls -lah $HOME/.cache/pypoetry
        echo "------------------"
        ls -lah $HOME/.cache/pypoetry/virtualenvs
        echo "------------------"
        ls -lah $HOME/.cache/pypoetry/cache
    # - name: Install Poetry
    #   run: pip install poetry
    # - name: Run Tests 2
    #   env:
    #     DJANGO_SETTINGS_MODULE: django_unchained.settings
    #   run: python -m poetry run ./manage.py test
